import gpiod
from pymavlink import mavutil
from maju import maju_fwd
#from turun import turun_
# from kanan import kanan_laterall
# from kiri import kiri_lateral
# from servo_open import servo_opn
#from servo_close import servo_cls
from stop import stop_4m
from OCVFkanan import main_Fkiri
from OCVStep1 import main_stp1
# from emergency import emergency_1

# from shutdown import shtdwn
# from opencv import main
import time

# def tes_q():
print("tes_q started")
# Create the connection
master = mavutil.mavlink_connection("/dev/ttyAMA0", baud=57600)
print("Connection created")
# Wait a heartbeat before sending commands
master.wait_heartbeat()
print("Heartbeat received")

# Arm
master.mav.command_long_send(
    master.target_system,
    master.target_component,
    mavutil.mavlink.MAV_CMD_COMPONENT_ARM_DISARM,
    0,
    1, 0, 0, 0, 0, 0, 0)

# wait until arming confirmed
print("Waiting for the vehicle to arm")
master.motors_armed_wait()
print('Armed!')

# from depth import set_target_depth
# set_target_depth(-2)
#stabilize()
#turun_()
# from mode import stabilize
# stabilize()
# time.sleep(2)
maju_fwd()
time.sleep(2)
maju_fwd()
time.sleep(2)
from mode import stabilize
stabilize()

maju_fwd()
time.sleep(2)
maju_fwd()
time.sleep(2)
maju_fwd()
time.sleep(2)
maju_fwd()
time.sleep(2)
maju_fwd()
time.sleep(2)
maju_fwd()
time.sleep(2)
maju_fwd()
time.sleep(2)
maju_fwd()
time.sleep(2)
maju_fwd()
time.sleep(2)
maju_fwd()
time.sleep(2)
maju_fwd()
time.sleep(2)
maju_fwd()
time.sleep(2)
maju_fwd()
time.sleep(2)
maju_fwd()
time.sleep(2)
maju_fwd()
time.sleep(2)
maju_fwd()
time.sleep(2)
maju_fwd()
maju_fwd()
time.sleep(2)
maju_fwd()
time.sleep(2)
maju_fwd()
time.sleep(2)
maju_fwd()
time.sleep(2)
maju_fwd()
time.sleep(2)
maju_fwd()
time.sleep(2)
maju_fwd()
time.sleep(2)
maju_fwd()
time.sleep(2)
maju_fwd()
time.sleep(2)
maju_fwd()
time.sleep(2)
maju_fwd()
time.sleep(2)
maju_fwd()
maju_fwd()
time.sleep(2)
maju_fwd()
time.sleep(2)
maju_fwd()
time.sleep(2)
maju_fwd()
time.sleep(2)
maju_fwd()
time.sleep(2)
maju_fwd()
time.sleep(2)
maju_fwd()
time.sleep(2)
maju_fwd()
time.sleep(2)
maju_fwd()
time.sleep(2)
maju_fwd()
time.sleep(2)
maju_fwd()
time.sleep(2)
maju_fwd()
maju_fwd()
time.sleep(2)
maju_fwd()
time.sleep(2)
maju_fwd()
time.sleep(2)
maju_fwd()
time.sleep(2)
maju_fwd()
time.sleep(2)
maju_fwd()
time.sleep(2)
maju_fwd()
time.sleep(2)
maju_fwd()
time.sleep(2)
maju_fwd()
time.sleep(2)
maju_fwd()
time.sleep(2)
maju_fwd()
time.sleep(2)
maju_fwd()
maju_fwd()
time.sleep(2)
maju_fwd()
time.sleep(2)
maju_fwd()
time.sleep(2)
maju_fwd()
time.sleep(2)
maju_fwd()
time.sleep(2)
maju_fwd()
time.sleep(2)
maju_fwd()
time.sleep(2)
maju_fwd()
time.sleep(2)
maju_fwd()
time.sleep(2)
maju_fwd()
time.sleep(2)
maju_fwd()
time.sleep(2)
maju_fwd()
#=======================
time.sleep(2)
maju_fwd()
time.sleep(2)
maju_fwd()
time.sleep(2)
maju_fwd()
time.sleep(2)
maju_fwd()
time.sleep(2)
maju_fwd()
time.sleep(2)
maju_fwd()
maju_fwd()
time.sleep(2)
maju_fwd()
time.sleep(2)
maju_fwd()
time.sleep(2)
maju_fwd()
time.sleep(2)
maju_fwd()
time.sleep(2)
maju_fwd()
time.sleep(2)
maju_fwd()
time.sleep(2)
maju_fwd()
time.sleep(2)
maju_fwd()
time.sleep(2)
maju_fwd()
time.sleep(2)
maju_fwd()
time.sleep(2)
maju_fwd()
maju_fwd()
time.sleep(2)
maju_fwd()
time.sleep(2)
maju_fwd()
time.sleep(2)
maju_fwd()
time.sleep(2)
maju_fwd()
time.sleep(2)
maju_fwd()
time.sleep(2)
maju_fwd()
time.sleep(2)
maju_fwd()
time.sleep(2)
maju_fwd()
time.sleep(2)
maju_fwd()
time.sleep(2)
maju_fwd()
time.sleep(2)
maju_fwd()

stop_4m()